name: Build Tweak

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: macos-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Theos
        run: |
          git clone --recursive https://github.com/theos/theos.git $HOME/theos
          echo "THEOS=$HOME/theos" >> $GITHUB_ENV

      - name: Install dependencies
        run: |
          brew install perl ldid
          sudo gem install ffi # 如果你用到 libidid 可以替换这个
          export THEOS=$HOME/theos

      - name: Build tweak
        run: |
          export THEOS=$HOME/theos
          make clean package

      - name: Upload .dylib
        uses: actions/upload-artifact@v3
        with:
          name: dylib-output
          path: .theos/obj/*.dylib

      - name: Show build output
        run: |
          ls -R .theos/obj
