name: Build .deb Package

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up dpkg
        run: sudo apt-get update && sudo apt-get install -y dpkg-dev ldid

      - name: Build .deb package
        run: |
          mkdir -p build/DEBIAN
          cp control build/DEBIAN/
          mkdir -p build/Library/MobileSubstrate/DynamicLibraries
          cp TiktokCleaner.plist build/Library/MobileSubstrate/DynamicLibraries/
          cp TiktokCleaner.dylib build/Library/MobileSubstrate/DynamicLibraries/
          dpkg-deb --build build TiktokCleaner.deb

      - name: Upload Artifact
        uses: actions/upload-artifact@v3
        with:
          name: TiktokCleaner.deb
          path: TiktokCleaner.deb
