name: Build .deb Package

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up dpkg-deb
        run: sudo apt-get update && sudo apt-get install -y dpkg-dev

      - name: Build .deb package
        run: |
          dpkg-deb --build ./TiktokCleaner ./TiktokCleaner.deb

      - name: Upload .deb artifact
        uses: actions/upload-artifact@v4
        with:
          name: TiktokCleaner
          path: ./TiktokCleaner.deb
