name: build

on:
  push:
    branches: [main]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Theos environment
        run: |
          sudo apt update
          sudo apt install -y ldid dpkg-dev make clang git perl unzip zip curl rsync
          git clone --recursive https://github.com/theos/theos.git $HOME/theos
          echo "export THEOS=$HOME/theos" >> $GITHUB_ENV

      - name: Build dylib
        run: |
          make
          echo "当前目录文件结构如下："
          ls -R .theos/obj || echo "目录不存在"

      - name: Upload .dylib
        uses: actions/upload-artifact@v3
        with:
          name: dylib
          path: .theos/obj/*.dylib
