name: Build .dylib

on:
  push:
    branches: [main]

jobs:
  build:
    runs-on: macos-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Install dependencies
      run: |
        brew install ldid make dpkg

    - name: Set up Theos
      run: |
        git clone --recursive https://github.com/theos/theos.git ~/theos
        echo "THEOS=~/theos" >> $GITHUB_ENV

    - name: Build .dylib with Theos
      run: |
        make clean
        make

    - name: Upload .dylib artifact
      uses: actions/upload-artifact@v3
      with:
        name: TiktokCleaner.dylib
        path: obj/TiktokCleaner.dylib
